/**
 * "Jede Koerperempfindung soll ihre eigene ausfuehrliche 'kann'-
 * Erklaerung haben, statt sich die Zonen-Beschreibung zu teilen"-
 * Auftrag — one bespoke, open-ended description per sensation term
 * (all 70 from BODY_SENSATIONS_DE), replacing the shared six-zone
 * hint that every sensation in a zone used to show identically.
 * Same open-possibility phrasing style as the zone texts ("kann
 * bedeuten...", "oft ein Zeichen von...") — never a definite claim,
 * and never a diagnosis. Colour/zone assignment itself is untouched
 * (still sensationZones.ts) — this is purely the descriptive text
 * shown when a person looks at one specific sensation.
 */
export const SENSATION_DESCRIPTIONS_DE: Record<string, string> = {
  // Zone 1 — Regeneration & Pause
  'schwere Augen': 'Die Augen fühlen sich müde und schwer an. Kann echte Müdigkeit sein, nach der der Körper gerade verlangt — oder ein Zeichen, dass gerade viel verarbeitet wird und der Körper sich abschirmt.',
  benommen: 'Ein dumpfes, wattiges Gefühl im Kopf. Kann für tiefe Entspannung stehen — oder dafür, dass gerade viel auf einmal war und der Kopf eine Pause braucht.',
  warm: 'Eine angenehme Wärme im Körper. Oft ein Zeichen von Geborgenheit oder Sicherheit — manchmal auch einfach die Raumtemperatur.',
  ruhig: 'Ein stilles, unaufgeregtes Gefühl im Körper. Kann echte innere Ruhe sein — oder der Moment direkt nach einer Anspannung, bevor sich wieder etwas regt.',
  entspannt: 'Die Muskeln fühlen sich gelöst an, nichts drückt oder zieht. Meist ein Zeichen, dass der Körper gerade nichts abwehren muss.',
  leicht: 'Der Körper fühlt sich mühelos an, fast schwerelos. Kann Erleichterung sein — etwa nach etwas, das gerade losgelassen wurde.',
  'angenehm wach': 'Wach, aber ohne Anspannung. Ein Zustand, in dem der Kopf klar ist, ohne dass der Körper unter Strom steht.',
  weich: 'Nichts fühlt sich hart oder angespannt an. Oft ein Zeichen von Sicherheit — der Körper muss sich gerade nicht wappnen.',
  'ruhig atmend': 'Der Atem geht gleichmäßig, ohne Anstrengung. Meist ein verlässliches Zeichen, dass das Nervensystem gerade nicht alarmiert ist.',
  gelöst: 'Eine Spannung, die da war, ist gerade gewichen. Kann direkt nach einer Anspannung besonders deutlich spürbar sein.',
  stabil: 'Der Körper fühlt sich getragen und sicher an, wie auf festem Boden. Oft ein Zeichen von Grundsicherheit.',
  'angenehm schwer': 'Eine wohlige Schwere, anders als Erschöpfung — eher wie nach echter Entspannung oder einem guten Ausruhen.',
  Magenknurren: 'Meist einfach Hunger — ein ganz alltägliches Körpersignal, das nicht mehr bedeuten muss als das.',

  // Zone 2 — Fokus & Flow
  energiegeladen: 'Der Körper fühlt sich kraftvoll und einsatzbereit an. Kann echte Energie sein — oder auch leichte Aufregung, die sich positiv anfühlt.',
  wach: 'Präsent und aufmerksam, ohne Anspannung. Oft ein guter Zustand zum Denken und Handeln.',
  'gleichmäßige Atmung': 'Der Atem fließt ruhig und regelmäßig. Ein verlässliches Zeichen für inneres Gleichgewicht.',
  'ruhiger Puls': 'Das Herz schlägt gleichmäßig, ohne dass man es besonders spürt — meist ein Zeichen von Ausgeglichenheit.',
  'aufrechte Grundspannung': 'Der Körper hält sich von selbst aufrecht, ohne Anstrengung — weder schlaff noch verkrampft.',
  'klarer Blick': 'Die Augen fühlen sich wach und fokussiert an. Oft ein Zeichen von Präsenz im Moment.',
  'entspannte Stirn': 'Keine Falten, kein Zusammenziehen — oft ein Zeichen, dass gerade nichts Sorgen bereitet.',
  'klarer Kopf': 'Gedanken lassen sich gut ordnen, nichts fühlt sich vernebelt an. Ein guter Zustand für Entscheidungen.',

  // Zone 3 — Grenzzone
  'innere Unruhe': 'Ein Gefühl, das sich schwer festmachen lässt — als würde etwas drängen. Kann ein erstes Zeichen steigender Anspannung sein.',
  Druck: 'Ein spürbares Gewicht oder Ziehen, oft im Brustkorb oder Kopf. Kann auf beginnende Überlastung hindeuten.',
  'flache Atmung': 'Der Atem wird kürzer, bleibt eher im oberen Brustkorb. Ein häufiges, frühes Zeichen von Anspannung.',
  'Atmung im Brustkorb': 'Der Atem fühlt sich hoch an, statt tief in den Bauch zu gehen. Oft ein Zeichen, dass sich der Körper bereitmacht.',
  'Puls im Hals spürbar': 'Das eigene Herz wird spürbar, besonders im Hals. Kann auf steigende Erregung hindeuten.',
  'Verspannung im Nacken': 'Der Nacken fühlt sich fest oder verkrampft an — eine häufige Stelle, an der sich Anspannung zeigt.',
  'hochgezogene Schultern': 'Die Schultern ziehen sich Richtung Ohren, oft unbemerkt. Ein klassisches Zeichen von Anspannung oder Schreckhaftigkeit.',
  'hektischer Blick': 'Die Augen springen schnell zwischen Dingen hin und her. Kann ein Zeichen von Wachsamkeit oder innerer Unruhe sein.',
  Kieferpresse: 'Die Kiefermuskeln ziehen sich zusammen, ohne dass man es bewusst tut. Ein häufiges Zeichen unbewusster Anspannung.',
  'feuchte Hände': 'Die Hände werden schwitzig, oft plötzlich. Ein klassisches, gut bekanntes Stresssignal des Körpers.',
  Hitzewallungen: 'Plötzliche Wärme, die durch den Körper zieht. Kann mit Aufregung oder Anspannung zusammenhängen.',
  'Flauen im Magen': 'Ein unruhiges, leicht flaues Gefühl im Bauch. Oft ein früher körperlicher Hinweis auf Nervosität.',
  'zusammengezogener Magen': 'Der Magen fühlt sich eng oder verkrampft an. Kann mit Sorge oder Anspannung zusammenhängen.',

  // Zone 4 — Hyperarousal
  Herzklopfen: 'Das Herz schlägt spürbar schneller oder kräftiger. Ein deutliches Zeichen, dass der Körper in Alarmbereitschaft geht.',
  angespannt: 'Muskeln sind angezogen, bereit für etwas. Ein Zeichen, dass sich der Körper auf Handeln vorbereitet.',
  Zittern: 'Ein feines oder stärkeres Beben, oft in Händen oder Beinen. Häufig ein Zeichen, dass viel Energie im Körper freigesetzt wurde.',
  Kribbeln: 'Ein prickelndes Gefühl, oft in Armen oder Beinen. Kann mit erhöhter Erregung zusammenhängen.',
  Übelkeit: 'Ein flaues bis unangenehmes Gefühl im Magen. Ein Körpersignal, das bei starker Anspannung häufig auftritt.',
  heiß: 'Eine plötzliche, oft unangenehme Hitze im Körper. Anders als angenehme Wärme — eher ein Zeichen von Aktivierung.',
  'kalte Hände': 'Die Hände werden kühl, oft während der Rest des Körpers heiß wird — das Blut zieht sich zu den großen Muskeln zurück.',
  'wackelige Beine': 'Die Beine fühlen sich unsicher oder zitterig an. Häufig während oder direkt nach starker Anspannung.',
  'trockener Mund': 'Der Speichelfluss reduziert sich spürbar. Ein bekanntes Zeichen von Stress oder Aufregung.',
  'angespannter Kiefer': 'Der Kiefer presst sich fest zusammen, deutlicher als eine leichte Kieferpresse — oft kaum bewusst wahrgenommen.',
  'zugeschnürte Kehle': 'Ein Engegefühl im Hals, als würde sich etwas zusammenziehen. Kann mit starker Anspannung einhergehen.',
  'rasender Puls': 'Das Herz schlägt sehr schnell, deutlich spürbar. Ein starkes Zeichen von Aktivierung.',
  'Fäuste ballen': 'Die Hände ziehen sich von selbst zusammen. Ein Zeichen von Kampf-Bereitschaft im Körper.',
  Tunnelblick: 'Der Blick verengt sich auf einen Punkt, das Drumherum verschwimmt. Ein bekanntes Zeichen starker Erregung.',
  'kalter Schweiß': 'Schweiß, der sich kühl statt warm anfühlt. Häufig bei starker Anspannung oder Schreck.',
  'Stechen im Magen': 'Ein scharfes, plötzliches Gefühl im Bauch. Kann mit akuter Anspannung zusammenhängen.',
  Schwindel: 'Ein Gefühl von Unsicherheit oder Drehen. Kann viele Gründe haben — starke Anspannung ist einer davon.',

  // Zone 5 — Mischzustand / Freeze
  'Kloß im Hals': 'Ein Engegefühl, als würde etwas im Hals stecken. Oft ein Zeichen von Gefühlen, die gerade zurückgehalten werden.',
  'Enge im Brustkorb': 'Der Brustkorb fühlt sich eingeengt an, als könnte man nicht ganz durchatmen.',
  'Atem anhalten': 'Der Atem stoppt kurz, oft unbemerkt. Ein altes Schutzmuster des Körpers, um still zu werden.',
  'wie eingemauert': 'Ein Gefühl von Starre, als könnte man sich nicht bewegen. Ein Zeichen, dass der Körper gerade "einfriert".',
  'eingefrorene Mimik': 'Das Gesicht fühlt sich unbeweglich an. Kann mit dem Gefühl von Feststecken zusammenhängen.',
  Schluckbeschwerden: 'Schlucken fällt schwer oder fühlt sich blockiert an. Oft mit Anspannung im Hals verbunden.',
  'Druck im Kopf': 'Ein Gefühl von Enge oder Gewicht im Kopf — anders als Watte im Kopf, eher wie Anspannung, die sich staut.',

  // Zone 6 — Shutdown
  leer: 'Ein Gefühl von Nichts, als wäre da gerade wenig zu spüren. Oft ein Zeichen, dass sich der Körper zurückzieht.',
  'taube Hände/Füße': 'Wenig bis kein Gefühl mehr in Händen oder Füßen. Ein Zeichen, dass der Körper gerade auf Sparflamme läuft.',
  'schwere Glieder': 'Arme und Beine fühlen sich extrem schwer an, kaum zu bewegen. Anders als angenehme Schwere — eher erschöpft.',
  frieren: 'Eine Kälte, die von innen kommt. Kann ein Zeichen sein, dass sich der Körper herunterfährt.',
  'sehr flache Atmung': 'Der Atem wird kaum merklich. Ein Zeichen tiefer Abschaltung.',
  'Blutdruck sackt ab': 'Ein Gefühl von Schwäche oder Benommenheit, manchmal mit Schwindel. Der Körper reduziert gerade seine Aktivität.',
  'schlaffe Muskeln': 'Muskeln verlieren ihre Spannung fast komplett, fühlen sich kraftlos an. Ein Zeichen von tiefer Abschaltung.',
  'wie durch Watte': 'Die Welt fühlt sich gedämpft an, wie durch eine Schicht hindurch. Ein bekanntes Zeichen von Dissoziation.',
  'Watte im Kopf': 'Ähnlich wie "wie durch Watte", aber speziell im Kopf — Gedanken lassen sich gerade schwer fassen.',
  'aus dem Körper schweben': 'Ein Gefühl, den eigenen Körper aus der Distanz wahrzunehmen. Ein bekanntes Zeichen von Dissoziation.',
  sprachlos: 'Worte lassen sich gerade nicht finden. Kann mit Überwältigung oder einem Shutdown-Zustand zusammenhängen.',
  'glanzloser Blick': 'Die Augen wirken leer oder abwesend. Oft ein äußeres Zeichen von innerem Rückzug.',
};

export const SENSATION_DESCRIPTIONS_EN: Record<string, string> = {
  'schwere Augen': 'Eyes feel tired and heavy. Can be real tiredness the body is asking for — or a sign that a lot has been processed and the body is shielding itself.',
  benommen: 'A dull, foggy feeling in the head. Can mean deep relaxation — or that there was a lot at once and the head needs a break.',
  warm: 'A pleasant warmth in the body. Often a sign of safety or comfort — sometimes just the room temperature.',
  ruhig: 'A still, unhurried feeling in the body. Can be genuine inner calm — or the moment right after tension, before something stirs again.',
  entspannt: 'Muscles feel loose, nothing pulling or pressing. Usually a sign the body has nothing to guard against right now.',
  leicht: 'The body feels effortless, almost weightless. Can be relief — often after letting something go.',
  'angenehm wach': 'Alert but without tension. A state where the mind is clear without the body being on high alert.',
  weich: 'Nothing feels hard or tense. Often a sign of safety — the body doesn\'t need to brace right now.',
  'ruhig atmend': 'Breath flows evenly, without effort. Usually a reliable sign the nervous system isn\'t on alert right now.',
  gelöst: 'A tension that was there has just eased. Can feel especially noticeable right after tension.',
  stabil: 'The body feels held and secure, like solid ground. Often a sign of basic safety.',
  'angenehm schwer': 'A pleasant heaviness, different from exhaustion — more like after real relaxation or good rest.',
  Magenknurren: 'Usually just hunger — an everyday body signal that doesn\'t have to mean more than that.',
  energiegeladen: 'The body feels strong and ready. Can be real energy — or excitement that feels good.',
  wach: 'Present and attentive, without tension. Often a good state for thinking and acting.',
  'gleichmäßige Atmung': 'Breath flows calmly and regularly. A reliable sign of inner balance.',
  'ruhiger Puls': 'The heart beats evenly, barely noticeable — usually a sign of balance.',
  'aufrechte Grundspannung': 'The body holds itself upright on its own, without effort — neither slack nor rigid.',
  'klarer Blick': 'Eyes feel alert and focused. Often a sign of presence in the moment.',
  'entspannte Stirn': 'No furrowing, no tightening — often a sign that nothing is worrying right now.',
  'klarer Kopf': 'Thoughts sort themselves easily, nothing feels foggy. A good state for decisions.',
  'innere Unruhe': 'A feeling that\'s hard to pin down — as if something is pushing. Can be an early sign of rising tension.',
  Druck: 'A noticeable weight or pulling, often in the chest or head. Can point to building overload.',
  'flache Atmung': 'Breath gets shorter, staying higher in the chest. A common early sign of tension.',
  'Atmung im Brustkorb': 'Breath feels high rather than reaching deep into the belly. Often a sign the body is bracing.',
  'Puls im Hals spürbar': 'Your own heartbeat becomes noticeable, especially in the throat. Can point to rising activation.',
  'Verspannung im Nacken': 'The neck feels tight or knotted — a common place where tension shows up.',
  'hochgezogene Schultern': 'Shoulders creep toward the ears, often unnoticed. A classic sign of tension or being startled.',
  'hektischer Blick': 'Eyes dart quickly between things. Can be a sign of vigilance or inner unrest.',
  Kieferpresse: 'Jaw muscles clench without deciding to. A common sign of unconscious tension.',
  'feuchte Hände': 'Hands get sweaty, often suddenly. A well-known stress signal from the body.',
  Hitzewallungen: 'Sudden warmth sweeping through the body. Can relate to excitement or tension.',
  'Flauen im Magen': 'An unsettled, slightly queasy feeling in the stomach. Often an early bodily hint of nervousness.',
  'zusammengezogener Magen': 'The stomach feels tight or clenched. Can relate to worry or tension.',
  Herzklopfen: 'The heart beats noticeably faster or harder. A clear sign the body is going on alert.',
  angespannt: 'Muscles are drawn tight, ready for something. A sign the body is preparing to act.',
  Zittern: 'A fine or stronger shaking, often in hands or legs. Often a sign that a lot of energy was just released in the body.',
  Kribbeln: 'A tingling feeling, often in arms or legs. Can relate to heightened activation.',
  Übelkeit: 'A queasy, unpleasant feeling in the stomach. A body signal that often shows up with strong tension.',
  heiß: 'A sudden, often uncomfortable heat in the body. Different from pleasant warmth — more a sign of activation.',
  'kalte Hände': 'Hands turn cool while the rest of the body heats up — blood pulling back toward the large muscles.',
  'wackelige Beine': 'Legs feel unsteady or shaky. Common during or right after strong tension.',
  'trockener Mund': 'Saliva noticeably decreases. A well-known sign of stress or excitement.',
  'angespannter Kiefer': 'The jaw clenches firmly, more than a light jaw-press — often barely noticed consciously.',
  'zugeschnürte Kehle': 'A tightness in the throat, as if something is closing. Can go along with strong tension.',
  'rasender Puls': 'The heart races, clearly noticeable. A strong sign of activation.',
  'Fäuste ballen': 'Hands clench on their own. A sign of the body readying to fight.',
  Tunnelblick: 'Vision narrows to one point, everything else blurs. A well-known sign of strong activation.',
  'kalter Schweiß': 'Sweat that feels cool rather than warm. Common with strong tension or shock.',
  'Stechen im Magen': 'A sharp, sudden feeling in the stomach. Can relate to acute tension.',
  Schwindel: 'A feeling of unsteadiness or spinning. Can have many causes — strong tension is one of them.',
  'Kloß im Hals': 'A tightness as if something is stuck in the throat. Often a sign of feelings being held back.',
  'Enge im Brustkorb': 'The chest feels constricted, as if a full breath isn\'t quite possible.',
  'Atem anhalten': 'Breath stops briefly, often unnoticed. An old protective pattern for going still.',
  'wie eingemauert': 'A feeling of rigidity, as if you can\'t move. A sign the body is "freezing".',
  'eingefrorene Mimik': 'The face feels unable to move. Can relate to the feeling of being stuck.',
  Schluckbeschwerden: 'Swallowing feels hard or blocked. Often tied to tension in the throat.',
  'Druck im Kopf': 'A feeling of tightness or weight in the head — different from brain fog, more like tension building up.',
  leer: 'A feeling of nothing, as if there\'s little to sense right now. Often a sign the body is pulling back.',
  'taube Hände/Füße': 'Little to no feeling left in hands or feet. A sign the body is running on low power.',
  'schwere Glieder': 'Arms and legs feel extremely heavy, hard to move. Different from pleasant heaviness — more exhausted.',
  frieren: 'A cold that comes from within. Can be a sign the body is shutting down.',
  'sehr flache Atmung': 'Breath becomes barely noticeable. A sign of deep shutdown.',
  'Blutdruck sackt ab': 'A feeling of weakness or faintness, sometimes with dizziness. The body reducing its activity.',
  'schlaffe Muskeln': 'Muscles lose almost all their tone, feel powerless. A sign of deep shutdown.',
  'wie durch Watte': 'The world feels muffled, as if through a layer. A well-known sign of dissociation.',
  'Watte im Kopf': 'Similar to feeling muffled, but specifically in the head — thoughts are hard to grasp right now.',
  'aus dem Körper schweben': 'A feeling of watching your own body from a distance. A well-known sign of dissociation.',
  sprachlos: 'Words are hard to find right now. Can relate to overwhelm or a shutdown state.',
  'glanzloser Blick': 'Eyes look empty or absent. Often an outward sign of inner withdrawal.',
};
