import {
  User,
  MapPin,
  Sparkles,
  BookHeart,
  Heart,
  Home,
  Coffee,
  Music,
  Sun,
  Moon,
  TreePine,
  Phone,
  MessageCircle,
  Star,
  Gift,
  Dog,
  Umbrella,
  Book,
  Flower2,
  Cloud,
  Flame,
  Snowflake,
  Anchor,
  Feather,
  Gamepad2,
  Palette,
  Camera,
  Bike,
  Waves,
  Mountain,
  Cat,
  Bird,
  Leaf,
  Sparkle,
  PawPrint,
  Users,
  Building2,
  Backpack,
  Utensils,
  BedDouble,
  type LucideIcon,
} from 'lucide-react';

/**
 * Every icon a node or category can display, keyed by a stable string so it
 * can be persisted. Deliberately broad (people, places, comforts, nature,
 * activities) so most personal network entries can find a fitting symbol.
 */
export const ICONS_BY_KEY: Record<string, LucideIcon> = {
  user: User,
  mapPin: MapPin,
  sparkles: Sparkles,
  bookHeart: BookHeart,
  heart: Heart,
  home: Home,
  coffee: Coffee,
  music: Music,
  sun: Sun,
  moon: Moon,
  treePine: TreePine,
  phone: Phone,
  messageCircle: MessageCircle,
  star: Star,
  gift: Gift,
  dog: Dog,
  umbrella: Umbrella,
  book: Book,
  flower: Flower2,
  cloud: Cloud,
  flame: Flame,
  snowflake: Snowflake,
  anchor: Anchor,
  feather: Feather,
  gamepad: Gamepad2,
  palette: Palette,
  camera: Camera,
  bike: Bike,
  waves: Waves,
  mountain: Mountain,
  cat: Cat,
  bird: Bird,
  leaf: Leaf,
  sparkle: Sparkle,
  pawPrint: PawPrint,
  users: Users,
  building: Building2,
  backpack: Backpack,
  utensils: Utensils,
  bed: BedDouble,
};

export const ICON_PICKER_ORDER = [
  'user',
  'users',
  'mapPin',
  'home',
  'building',
  'heart',
  'bookHeart',
  'sparkles',
  'sparkle',
  'star',
  'sun',
  'moon',
  'cloud',
  'flame',
  'snowflake',
  'coffee',
  'utensils',
  'music',
  'gamepad',
  'palette',
  'camera',
  'book',
  'treePine',
  'flower',
  'leaf',
  'mountain',
  'waves',
  'anchor',
  'feather',
  'bike',
  'backpack',
  'bed',
  'phone',
  'messageCircle',
  'gift',
  'umbrella',
  'dog',
  'cat',
  'bird',
  'pawPrint',
];

export function getIcon(key: string | undefined, fallback: string): LucideIcon {
  return (key && ICONS_BY_KEY[key]) || ICONS_BY_KEY[fallback] || Sparkles;
}
